#!make
#
# $Id$
#
# Copyright (c) 2005 Steven Bakker, AMS-IX B.V.;
#
# See the LICENCE file that came with this package.

TOPDIR	=	..

include $(TOPDIR)/config.mk
include $(TOPDIR)/rules.mk

default		:	all

all		:	M6-all

install		:	M6-install

clean		:	M6-clean

veryclean	:	M6-veryclean
