# $Id$
#
# Copyright (c) 2002 Steven Bakker.
#
TOPDIR		=	../../..

include $(TOPDIR)/config.mk


INSTALLDIR	=	$(INSTLIB)/M6/ARP

INSTALLFILES		=	\
				$(INSTALLDIR)/Queue.pm		\
				$(INSTALLDIR)/Sponge.pm		\
				$(INSTALLDIR)/Table.pm		\
				$(INSTALLDIR)/Util.pm

include $(TOPDIR)/rules.mk

# E.O.F. Makefile
