# $Id$
#
# Copyright (c) 2002 Steven Bakker.
#
TOPDIR		=	../../../..

include $(TOPDIR)/config.mk


INSTALLDIR	=	$(INSTLIB)/M6/ARP/Control

INSTALLFILES		=	\
				$(INSTALLDIR)/Base.pm		\
				$(INSTALLDIR)/Client.pm		\
				$(INSTALLDIR)/Server.pm

include $(TOPDIR)/rules.mk

# E.O.F. Makefile
