#!make
#
# $Id$
#
#  (c) Copyright 2005 Steven Bakker, AMS-IX B.V.
#
#  See the LICENSE file that came with this package.
#
include ../config.mk

TOPDIR		=	..

TARGETS		= 

INSTALLDIR  = $(DOCDIR)

INSTALLFILES	= \
			$(DOCDIR)/arpsponge_architecture.txt

include ../rules.mk

# E.O.F. Makefile
