#!make
#
# $Id$
#
#  (c) Copyright 2005 Steven Bakker, AMS-IX B.V.
#
#  See the LICENSE file that came with this package.
#
include ../config.mk

TOPDIR		=	..

INSTALLDIRS	=	$(BINDIR)

TARGETS		=	\
			arpswiffer

INSTALLFILES	=	\
			$(BINDIR)/arpswiffer

include ../rules.mk

# E.O.F. Makefile
