Document: arpswiffer
Title: Debian arpswiffer Manual
Author: <insert document author here>
Abstract: This manual describes what arpswiffer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/arpswiffer/arpswiffer.sgml.gz

Format: postscript
Files: /usr/share/doc/arpswiffer/arpswiffer.ps.gz

Format: text
Files: /usr/share/doc/arpswiffer/arpswiffer.text.gz

Format: HTML
Index: /usr/share/doc/arpswiffer/html/index.html
Files: /usr/share/doc/arpswiffer/html/*.html

  
