#!make
#
# $Id$
#
# Copyright (c) 2005 Steven Bakker, AMS-IX B.V.;
#
# See the LICENCE file that came with this package.

TOPDIR	=	../..

include $(TOPDIR)/config.mk

INSTALLDIR	=	$(INSTLIB)/M6

INSTALLFILES		=	\
				$(INSTALLDIR)/ReadLine.pm

include $(TOPDIR)/rules.mk

all			:	ARP-all

install		:	ARP-install

clean		:	ARP-clean

veryclean	:	ARP-veryclean

# E.O.F. Makefile
