#!/usr/bin/perl -n
#
SWITCH:{
	/^\#NODIST/                    && do{
		$nodist = 1;
		last SWITCH};
	($nodist && /^\#END-NODIST/)   && do{
		$nodist = 0;
		last SWITCH};
	!$nodist                       && do{
		print;
		last SWITCH};
}
