# $Id$
#
# Copyright (c) 2002 Steven Bakker.
#
TOPDIR		=	../../..

include $(TOPDIR)/config.mk


INSTALLDIR	=	$(INSTLIB)/M6/ARP

INSTALLFILES		=	\
		$(INSTALLDIR)/Base.pm \
		$(INSTALLDIR)/Const.pm \
		$(INSTALLDIR)/Control.pm \
		$(INSTALLDIR)/Log.pm \
		$(INSTALLDIR)/NetPacket.pm \
		$(INSTALLDIR)/Queue.pm \
		$(INSTALLDIR)/Sponge.pm \
		$(INSTALLDIR)/Table.pm \
		$(INSTALLDIR)/Util.pm

include $(TOPDIR)/rules.mk

all			:	Control-all

install		:	Control-install

clean		:	Control-clean

veryclean	:	Control-veryclean

# E.O.F. Makefile
