#!make
#
#  Copyright 2005-2016 AMS-IX B.V.
#
#  This is free software. It can be distributed under
#  your choice of the GPL or Artistic License 2.0.
#
#  See the Copying file that came with this package.

TOPDIR	=	../..

include $(TOPDIR)/config.mk

include $(TOPDIR)/rules.mk

all			:	ArpSponge-all

install		:	ArpSponge-install

clean		:	ArpSponge-clean

veryclean	:	ArpSponge-veryclean

# E.O.F. Makefile
